
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvizhodhphttndvawcmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2aXpob2RocGh0dG5kdmF3Y21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjQ0MDMsImV4cCI6MjA2MDcwMDQwM30.akG0uom9a04t3rfzwpW17Gq0EmXdinU8Tfm8T2uNsxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
